; PlatformIO Project Configuration File
; This file defines the build, upload, and library options for the project.
; For detailed documentation, visit: https://docs.platformio.org/page/projectconf.html

[platformio]
description = Puara module OSC-Duplex template

[common]
; Define the platform and framework used for this project
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
framework = arduino

lib_deps = 
	https://github.com/Puara/puara-module.git
	https://github.com/cnmat/OSC#3.5.8
    https://github.com/thomasfredericks/MicroOsc.git
    https://github.com/mhroth/tinyosc.git
    https://github.com/eddietree/oscpkt.git

board_build.partitions = min_spiffs_no_OTA.csv
monitor_speed = 115200
monitor_echo = yes
monitor_filters = default esp32_exception_decoder

; Filesystem options:
; Uncomment one of the following lines to select the filesystem:
board_build.filesystem = littlefs ; Default: LittleFS
;board_build.filesystem = spiffs  ; Use SPIFFS instead (requires -DPUARA_SPIFFS flag)

[env:template]
extends = common
board = tinypico  ; Change board here, ex: tinypico, esp32-c3-devkitc-02, seeed_xiao_esp32s3
build_flags =
    -DBOARD_HAS_PSRAM
    ;-DPUARA_SPIFFS ; compilation flag to indicate the usage of spiffs lib instead of littlefs. Default is littlefs
    -mfix-esp32-psram-cache-issue ; you may need to comment out this line with some boards if it gives you error messages such as with esp32-c3-devkitc-02
    -std=gnu++2a
build_unflags = -std=c++11 -std=c++14 -std=c++17 -std=gnu++11 -std=gnu++14 -std=gnu++17
platform_packages = espressif/toolchain-xtensa-esp32@12.2.0+20230208
board_build.sdkconfig = sdkconfig.defaults
